name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 coverage
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 polymnia --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 polymnia --count --exit-zero --max-complexity=10 --max-line-length=130 --statistics
    - name: Test with pytest
      run: |
        coverage run -m unittest discover polymnia.tests
        coverage xml
    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@0.2.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.xml